#include <iostream>
#include <string>

using namespace std;

int main(){
    int a;
    int b = 100;
    int *c;
    int *d = &b;
    int *e = d;
    int &f = b;
    int g = f;
    int h = *d;
    int i = h;
    cout << "Test: a" << endl;
    cout << "a = " << a << endl;
    cout << "&a = " << &a << endl;
    cout << "*&a = " << *&a << endl;
    cout << "&*&a = " << &*&a << endl;
    cout << "*&*&a = " << *&*&a << endl;
    cout << "&*&*&a = " << &*&*&a << endl;
    cout << endl << "Test: b = 100" << endl;
    cout << "b = " << b << endl;
    cout << "&b = " << &b << endl;
    cout << "*&b = " << *&b << endl;
    cout << "&*&b = " << &*&b << endl;
    cout << "*&*&b = " << *&*&b << endl;
    cout << "&*&*&b = " << &*&*&b << endl;
    cout << endl << "Test: *c" << endl;
    cout << "c = " << c << endl;
    cout << "*c = " << *c << endl;
    cout << "&c = " << &c << endl;
    cout << "*&c = " << *&c << endl;
    cout << "&*c = " << &*c << endl;
    cout << "&*&c = " << &*&c << endl;
    cout << "*&*c = " << *&*c << endl;
    cout << "*&*&c = " << *&*&c << endl;
    cout << "&*&*c = " << &*&*c << endl;
    cout << "&*&*&c = " << &*&*&c << endl;
    cout << "*&*&*c = " << *&*&*c << endl;
    cout << endl << "Test: *d = &b, b = 100" << endl;
    cout << "d = " << d << endl;
    cout << "*d = " << *d << endl;
    cout << "&d = " << &d << endl;
    cout << "*&d = " << *&d << endl;
    cout << "&*d = " << &*d << endl;
    cout << "&*&d = " << &*&d << endl;
    cout << "*&*d = " << *&*d << endl;
    cout << "*&*&d = " << *&*&d << endl;
    cout << "&*&*d = " << &*&*d << endl;
    cout << "&*&*&d = " << &*&*&d << endl;
    cout << "*&*&*d = " << *&*&*d << endl;
    cout << endl << "Test: *e = d, *d = &b, b = 100" << endl;
    cout << "e = " << e << endl;
    cout << "*e = " << *e << endl;
    cout << "&e = " << &e << endl;
    cout << "*&e = " << *&e << endl;
    cout << "&*e = " << &*e << endl;
    cout << "&*&e = " << &*&e << endl;
    cout << "*&*e = " << *&*e << endl;
    cout << "*&*&e = " << *&*&e << endl;
    cout << "&*&*e = " << &*&*e << endl;
    cout << "&*&*&e = " << &*&*&e << endl;
    cout << "*&*&*e = " << *&*&*e << endl;
    cout << endl << "Test: &f = b, b = 100" << endl;
    cout << "f = " << f << endl;
    cout << "&f = " << &f << endl;
    cout << "*&f = " << *&f << endl;
    cout << "&*&f = " << &*&f << endl;
    cout << "*&*&f = " << *&*&f << endl;
    cout << "&*&*&f = " << &*&*&f << endl;
    cout << endl << "Test: g = f, &f = b, b = 100" << endl;
    cout << "g = " << g << endl;
    cout << "&g = " << &g << endl;
    cout << "*&g = " << *&g << endl;
    cout << "&*&g = " << &*&g << endl;
    cout << "*&*&g = " << *&*&g << endl;
    cout << "&*&*&g = " << &*&*&g << endl;
    cout << endl << "Test: h = *d, *d = &b, b = 100" << endl;
    cout << "h = " << h << endl;
    cout << "&h = " << &h << endl;
    cout << "*&h = " << *&h << endl;
    cout << "&*&h = " << &*&h << endl;
    cout << "*&*&h = " << *&*&h << endl;
    cout << "&*&*&h = " << &*&*&h << endl;
    cout << endl << "Test: i = h, h = *d, *d = &b, b = 100" << endl;
    cout << "i = " << i << endl;
    cout << "&i = " << &i << endl;
    cout << "*&i = " << *&i << endl;
    cout << "&*&i = " << &*&i << endl;
    cout << "*&*&i = " << *&*&i << endl;
    cout << "&*&*&i = " << &*&*&i << endl;
    b = 200;
    cout << endl << "Test: a" << endl;
    cout << "a = " << a << endl;
    cout << "&a = " << &a << endl;
    cout << "*&a = " << *&a << endl;
    cout << "&*&a = " << &*&a << endl;
    cout << "*&*&a = " << *&*&a << endl;
    cout << "&*&*&a = " << &*&*&a << endl;
    cout << endl << "Test: b = 100" << endl;
    cout << "b = " << b << endl;
    cout << "&b = " << &b << endl;
    cout << "*&b = " << *&b << endl;
    cout << "&*&b = " << &*&b << endl;
    cout << "*&*&b = " << *&*&b << endl;
    cout << "&*&*&b = " << &*&*&b << endl;
    cout << endl << "Test: *c" << endl;
    cout << "c = " << c << endl;
    cout << "*c = " << *c << endl;
    cout << "&c = " << &c << endl;
    cout << "*&c = " << *&c << endl;
    cout << "&*c = " << &*c << endl;
    cout << "&*&c = " << &*&c << endl;
    cout << "*&*c = " << *&*c << endl;
    cout << "*&*&c = " << *&*&c << endl;
    cout << "&*&*c = " << &*&*c << endl;
    cout << "&*&*&c = " << &*&*&c << endl;
    cout << "*&*&*c = " << *&*&*c << endl;
    cout << endl << "Test: *d = &b, b = 100" << endl;
    cout << "d = " << d << endl;
    cout << "*d = " << *d << endl;
    cout << "&d = " << &d << endl;
    cout << "*&d = " << *&d << endl;
    cout << "&*d = " << &*d << endl;
    cout << "&*&d = " << &*&d << endl;
    cout << "*&*d = " << *&*d << endl;
    cout << "*&*&d = " << *&*&d << endl;
    cout << "&*&*d = " << &*&*d << endl;
    cout << "&*&*&d = " << &*&*&d << endl;
    cout << "*&*&*d = " << *&*&*d << endl;
    cout << endl << "Test: *e = d, *d = &b, b = 100" << endl;
    cout << "e = " << e << endl;
    cout << "*e = " << *e << endl;
    cout << "&e = " << &e << endl;
    cout << "*&e = " << *&e << endl;
    cout << "&*e = " << &*e << endl;
    cout << "&*&e = " << &*&e << endl;
    cout << "*&*e = " << *&*e << endl;
    cout << "*&*&e = " << *&*&e << endl;
    cout << "&*&*e = " << &*&*e << endl;
    cout << "&*&*&e = " << &*&*&e << endl;
    cout << "*&*&*e = " << *&*&*e << endl;
    cout << endl << "Test: &f = b, b = 100" << endl;
    cout << "f = " << f << endl;
    cout << "&f = " << &f << endl;
    cout << "*&f = " << *&f << endl;
    cout << "&*&f = " << &*&f << endl;
    cout << "*&*&f = " << *&*&f << endl;
    cout << "&*&*&f = " << &*&*&f << endl;
    cout << endl << "Test: g = f, &f = b, b = 100" << endl;
    cout << "g = " << g << endl;
    cout << "&g = " << &g << endl;
    cout << "*&g = " << *&g << endl;
    cout << "&*&g = " << &*&g << endl;
    cout << "*&*&g = " << *&*&g << endl;
    cout << "&*&*&g = " << &*&*&g << endl;
    cout << endl << "Test: h = *d, *d = &b, b = 100" << endl;
    cout << "h = " << h << endl;
    cout << "&h = " << &h << endl;
    cout << "*&h = " << *&h << endl;
    cout << "&*&h = " << &*&h << endl;
    cout << "*&*&h = " << *&*&h << endl;
    cout << "&*&*&h = " << &*&*&h << endl;
    cout << endl << "Test: i = h, h = *d, *d = &b, b = 100" << endl;
    cout << "i = " << i << endl;
    cout << "&i = " << &i << endl;
    cout << "*&i = " << *&i << endl;
    cout << "&*&i = " << &*&i << endl;
    cout << "*&*&i = " << *&*&i << endl;
    cout << "&*&*&i = " << &*&*&i << endl;
}